### ISSUE TITLE
GNG Changes AIRAC 2410 EDDB

### ISSUE THREAD

**Issue by hannesaltmann** [VATGER-Nav/edww-package#363]
- [x] **Update all RWY-based sector activations (https://gng.aero-nav.com/EDWW/nav_sectors)**
- [x] Update all RWY-based local vACC COPX (https://gng.aero-nav.com/EDWW/nav_copxv)
- [x] Update all RWY-based global COPX (https://gng.aero-nav.com/EDWW/nav_copxg)
- [x] **Check if every data entry for EDDB is selected** (https://gng.aero-nav.com/EDWW/nav_data_selection)
- [x] **Update Procident and Transident for Proc Modify** (https://gng.aero-nav.com/EDWW/nav_proc_modify)
- [x] **Update Proc Combiner for EDDB** (https://gng.aero-nav.com/EDWW/nav_proc_combiner)

**Tasks in bold can only be performed once the new AIRAC is available at GNG.** All names of procedures are available here: https://gng.aero-nav.com/EDWW/nav_proc

**Comment by hannesaltmann** [comment]
Sektoren gehen wohl auch nur nach AIRAC Release
